services:
  dtls-server:
    build: .
    image: iiot-base-image
    container_name: iiot-dtls-server
    volumes:
      - ../traces:/traces
      - ./certs/server:/certs
      - ../scripts/capture-packets:/scripts/capture
      - ../scripts/setup-network:/scripts/setup
    cap_add:
      - NET_ADMIN
    environment:
      - RUN_TIMESTAMP=${RUN_TIMESTAMP}
    command: >
      /scripts/capture/capture-and-run.sh
        ${SCENARIO}
        dtls_server
        coap-server -v 8 -A 0.0.0.0 
          -c /certs/server.crt
          -j /certs/server.key
          -R /certs/ca.crt

  dtls-client:
    build: .
    image: iiot-base-image
    container_name: iiot-dtls-client
    volumes:
      - ../traces:/traces
      - ./certs/client:/certs
      - ../scripts/capture-packets:/scripts/capture
      - ../scripts/setup-network:/scripts/setup
    cap_add:
      - NET_ADMIN
    environment:
      - RUN_TIMESTAMP=${RUN_TIMESTAMP}
    depends_on:
      - dtls-server
    entrypoint: /bin/bash -c "sleep 5 && exec \"$$@\"" --
    command: >
      /scripts/capture/capture-and-run.sh
        ${SCENARIO}
        dtls_client
        coap-client -v 8 -m get 
          -c /certs/client.crt
          -j /certs/client.key
          -R /certs/ca.crt
          coaps://${DTLS_SERVER_IP}:5684/

  edhoc-server:
    build: .
    image: iiot-base-image
    container_name: iiot-edhoc-server
    volumes:
      - ../../build/bin:/app
      - ../traces:/traces
      - ../scripts/capture-packets:/scripts/capture
      - ../scripts/setup-network:/scripts/setup
    cap_add:
      - NET_ADMIN
    environment:
      - RUN_TIMESTAMP=${RUN_TIMESTAMP}
    command: >
      /scripts/capture/capture-and-run.sh
        ${SCENARIO}
        edhoc_server
        /app/server -s 2

  edhoc-client:
    build: .
    image: iiot-base-image
    container_name: iiot-edhoc-client
    volumes:
      - ../../build/bin:/app
      - ../traces:/traces
      - ../scripts/capture-packets:/scripts/capture
      - ../scripts/setup-network:/scripts/setup
    cap_add:
      - NET_ADMIN
    environment:
      - RUN_TIMESTAMP=${RUN_TIMESTAMP}
    depends_on:
      - edhoc-server
    entrypoint: /bin/bash -c "sleep 5 && exec \"$$@\"" --
    command: >
      /scripts/capture/capture-and-run.sh
        ${SCENARIO}
        edhoc_client
        /app/client -s 2 iiot-edhoc-server