#ifndef EDHOC_CREDENTIALS_CRED_PUB_DATA_H_
#define EDHOC_CREDENTIALS_CRED_PUB_DATA_H_

#include <stdint.h>

enum { CRED_EDHOC_PUB_PK_LENGTH = 65 };

extern const uint8_t CRED_EDHOC_PUB_CLI_PK[CRED_EDHOC_PUB_PK_LENGTH];
extern const uint8_t CRED_EDHOC_PUB_SRV_PK[CRED_EDHOC_PUB_PK_LENGTH];
extern const int32_t CRED_EDHOC_PUB_SRV_KID;
extern const int32_t CRED_EDHOC_PUB_CLI_KID;
extern const uint16_t CRED_EDHOC_PUB_SRV_PORT;
extern const char CRED_EDHOC_PUB_SRV_URI[];

#endif  // EDHOC_CREDENTIALS_CRED_PUB_DATA_H_
