#ifndef COMMON_EMULATION_STATUS_H_
#define COMMON_EMULATION_STATUS_H_

typedef enum {
  COM_EMULATION_SUCCESS = 0,
  COM_EMULATION_FAILURE = -1,
} com_emulation_status_t;

#endif  // COMMON_EMULATION_STATUS_H_