#ifndef PUBLIC_DATA_H
#define PUBLIC_DATA_H

#include <stdint.h>

enum { PUBLIC_DATA_PRE_GENERATED_PUBLIC_KEY_LEN = 65 };
extern const uint8_t
    CLIENT_PUBLIC_KEY[PUBLIC_DATA_PRE_GENERATED_PUBLIC_KEY_LEN];
extern const uint8_t
    SERVER_PUBLIC_KEY[PUBLIC_DATA_PRE_GENERATED_PUBLIC_KEY_LEN];

#endif